# Generated by Django 3.2.24 on 2024-02-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tag_tag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
